import { useMemo, useState, useEffect } from 'react';
import { useModStore } from '../../store/useModStore';
import { Swords, AlertTriangle, Plus, Trash2, Code2, Copy, Check } from 'lucide-react';
import Editor from '@monaco-editor/react';

// ─── Types ────────────────────────────────────────────────────────────────────

type CivilWarType = 'ideology' | 'independence' | 'separatist' | 'faction';

export interface CivilConflict {
  id: string;
  name: string;
  warType: CivilWarType;
  rebelTag: string;
  rebelIdeology: string;
  rebelMilStrength: number;
  startingState: string;
  triggerScript: string;
  onStartEffect: string;
  onEndLoseEffect: string;
  onEndWinEffect: string;
}

const newConflict = (): CivilConflict => ({
  id: `civil_war_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`,
  name: 'New Civil Conflict',
  warType: 'ideology',
  rebelTag: 'REB',
  rebelIdeology: 'syndicalist',
  rebelMilStrength: 30,
  startingState: '64',
  triggerScript: '# Condition that fires the civil war\nhas_stability < 0.30',
  onStartEffect: '# Effects when war starts\nhidden_effect = {\n\tset_country_flag = civil_war_started\n}',
  onEndLoseEffect: '# Effects if rebels win',
  onEndWinEffect: '# Effects if government wins',
});

const WAR_TYPES: { id: CivilWarType; label: string; desc: string; color: string }[] = [
  { id: 'ideology', label: 'Ideological War', desc: 'Rebels fight for an alternate ideology.', color: 'border-red-500/50 bg-red-500/5 text-red-300' },
  { id: 'independence', label: 'Independence War', desc: 'A region fights for independence.', color: 'border-amber-500/50 bg-amber-500/5 text-amber-300' },
  { id: 'separatist', label: 'Separatist Revolt', desc: 'Minor separatist uprising.', color: 'border-orange-500/50 bg-orange-500/5 text-orange-300' },
  { id: 'faction', label: 'Faction Schism', desc: 'Internal party/military split.', color: 'border-purple-500/50 bg-purple-500/5 text-purple-300' },
];

const KR_IDEOLOGIES = [
  'totalist', 'syndicalist', 'radical_socialist', 'social_democrat',
  'social_liberal', 'market_liberal', 'social_conservative',
  'authoritarian_democrat', 'paternal_autocrat', 'national_populist',
];

// ─── Component ────────────────────────────────────────────────────────────────

export default function CivilConflictEditor() {
  const { baseMod, civilConflicts, setCivilConflicts } = useModStore();
  const [selectedId, setSelectedId] = useState(civilConflicts[0]?.id || '');
  const [activeTab, setActiveTab] = useState<'trigger' | 'start' | 'win' | 'lose'>('trigger');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (civilConflicts.length === 0) {
      setCivilConflicts([newConflict()]);
    }
  }, [civilConflicts.length, setCivilConflicts]);

  const conflicts = civilConflicts;
  const selected = conflicts.find(c => c.id === selectedId) || conflicts[0] || newConflict();

  const update = (partial: Partial<CivilConflict>) =>
    setCivilConflicts(conflicts.map(c => c.id === selectedId ? { ...c, ...partial } : c));

  const addConflict = () => {
    const c = newConflict();
    setCivilConflicts([...conflicts, c]);
    setSelectedId(c.id);
  };

  const deleteConflict = (id: string) => {
    const remaining = conflicts.filter(c => c.id !== id);
    const next = remaining.length ? remaining : [newConflict()];
    setCivilConflicts(next);
    setSelectedId(next[0].id);
  };

  const generatedCode = useMemo(() => {
    const lines: string[] = [
      `### Civil Conflict: ${selected.name}`,
      `### Generated by HOI4 Mod Studio — Kaiserreich`,
      ``,
      `### Scripted Trigger`,
      `${selected.id}_can_start = {`,
      `\t${selected.triggerScript.split('\n').join('\n\t')}`,
      `}`,
      ``,
      `### Country Event to initiate the war`,
      `country_event = {`,
      `\tid = ${selected.id}.1`,
      `\ttitle = ${selected.id}.1.t`,
      `\tdesc = ${selected.id}.1.d`,
      `\tis_triggered_only = yes`,
      ``,
      `\toption = {`,
      `\t\tname = ${selected.id}.1.a`,
      `\t\t# Start Civil War`,
      `\t\tstart_civil_war = {`,
      `\t\t\tideology = ${selected.rebelIdeology}`,
      `\t\t\ttarget = ${selected.rebelTag}`,
      `\t\t\tsize = ${(selected.rebelMilStrength / 100).toFixed(2)}`,
      `\t\t\tstate = ${selected.startingState}`,
      `\t\t}`,
      `\t\t${selected.onStartEffect.split('\n').join('\n\t\t')}`,
      `\t}`,
      `}`,
      ``,
      `### on_civil_war_end effects — WIN`,
      `${selected.id}_government_wins = {`,
      `\t${selected.onEndWinEffect.split('\n').join('\n\t')}`,
      `}`,
      ``,
      `### on_civil_war_end effects — LOSE`,
      `${selected.id}_rebels_win = {`,
      `\t${selected.onEndLoseEffect.split('\n').join('\n\t')}`,
      `}`,
    ];
    return lines.join('\n');
  }, [selected]);

  if (baseMod !== 'kaiserreich') {
    return (
      <div className="w-full h-full flex items-center justify-center bg-[#121212]">
        <div className="text-center">
          <AlertTriangle size={48} className="text-amber-500 mx-auto mb-4 opacity-60" />
          <p className="text-gray-400 text-lg font-semibold">Civil Conflict Editor</p>
          <p className="text-gray-600 text-sm mt-2">Exclusive to <span className="text-amber-500">Kaiserreich</span>.</p>
        </div>
      </div>
    );
  }

  const copyCode = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const inputCls = "bg-[#121212] border border-gray-700 rounded px-3 py-2 text-sm text-white focus:border-amber-500 focus:outline-none w-full";
  const EDITOR_TABS: { id: typeof activeTab; label: string }[] = [
    { id: 'trigger', label: 'Trigger' },
    { id: 'start', label: 'On Start' },
    { id: 'win', label: 'Gov Wins' },
    { id: 'lose', label: 'Rebels Win' },
  ];
  const editorValue = activeTab === 'trigger' ? selected.triggerScript
    : activeTab === 'start' ? selected.onStartEffect
    : activeTab === 'win' ? selected.onEndWinEffect
    : selected.onEndLoseEffect;
  const editorKey = activeTab === 'trigger' ? 'triggerScript'
    : activeTab === 'start' ? 'onStartEffect'
    : activeTab === 'win' ? 'onEndWinEffect'
    : 'onEndLoseEffect';

  return (
    <div className="w-full h-full flex bg-[#121212] overflow-hidden">
      {/* ── Sidebar: Conflict List ── */}
      <div className="w-52 bg-[#1a1a1a] border-r border-gray-800 flex flex-col">
        <div className="p-3 border-b border-gray-800 flex items-center justify-between">
          <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider flex items-center gap-1.5">
            <Swords size={12} className="text-red-400" /> Conflicts
          </span>
          <button onClick={addConflict} className="p-1 rounded hover:bg-red-500/20 text-red-400">
            <Plus size={14} />
          </button>
        </div>
        <div className="flex-1 overflow-y-auto">
          {conflicts.map(c => {
            const wt = WAR_TYPES.find(w => w.id === c.warType)!;
            return (
              <button key={c.id} onClick={() => setSelectedId(c.id)}
                className={`w-full text-left px-3 py-3 border-b border-gray-800/60 transition-colors ${
                  c.id === selectedId ? 'bg-red-500/10 border-l-2 border-l-red-500' : 'hover:bg-white/5'
                }`}>
                <p className="text-sm font-medium text-white truncate">{c.name}</p>
                <p className={`text-[10px] mt-0.5 ${wt.color.split(' ')[0]}`}>{wt.label}</p>
                <p className="text-[10px] text-gray-600 mt-0.5 font-mono">{c.rebelTag}</p>
              </button>
            );
          })}
        </div>
      </div>

      {/* ── Center: Form ── */}
      <div className="flex-1 overflow-y-auto p-6 flex flex-col gap-5">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-red-500/10 flex items-center justify-center">
              <Swords size={20} className="text-red-400" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-gray-100">Civil Conflict Editor</h2>
              <p className="text-xs text-gray-500">Kaiserreich — start_civil_war Builder</p>
            </div>
          </div>
          <button onClick={() => deleteConflict(selected.id)} disabled={conflicts.length === 1}
            className="text-gray-600 hover:text-red-500 transition-colors disabled:opacity-30">
            <Trash2 size={16} />
          </button>
        </div>

        {/* Conflict type */}
        <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-4">
          <label className="text-xs font-semibold text-amber-500 uppercase tracking-wider block mb-3">Conflict Type</label>
          <div className="grid grid-cols-2 gap-2">
            {WAR_TYPES.map(wt => (
              <button key={wt.id} onClick={() => update({ warType: wt.id })}
                className={`p-3 rounded-lg border text-left transition-all ${
                  selected.warType === wt.id ? wt.color : 'border-gray-700 bg-[#111] hover:border-gray-600'
                }`}>
                <p className="text-xs font-bold text-white">{wt.label}</p>
                <p className="text-[10px] text-gray-500 mt-0.5">{wt.desc}</p>
              </button>
            ))}
          </div>
        </div>

        {/* Basic Settings */}
        <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-4 grid grid-cols-2 gap-4">
          <h3 className="text-xs font-semibold text-amber-500 uppercase tracking-wider col-span-2">Conflict Settings</h3>
          <div className="flex flex-col gap-1">
            <label className="text-xs text-gray-400">Conflict Name</label>
            <input type="text" value={selected.name} onChange={e => update({ name: e.target.value })} className={inputCls} />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs text-gray-400">Script ID</label>
            <input type="text" value={selected.id}
              onChange={e => update({ id: e.target.value.toLowerCase().replace(/\s+/g, '_') })}
              className={`${inputCls} font-mono text-red-400`} />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs text-gray-400">Rebel Country TAG</label>
            <input type="text" value={selected.rebelTag}
              onChange={e => update({ rebelTag: e.target.value.toUpperCase().slice(0, 3) })}
              className={`${inputCls} font-mono font-bold`} maxLength={3} />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs text-gray-400">Rebel Ideology</label>
            <select value={selected.rebelIdeology} onChange={e => update({ rebelIdeology: e.target.value })} className={inputCls}>
              {KR_IDEOLOGIES.map(i => <option key={i} value={i}>{i.replace(/_/g, ' ')}</option>)}
            </select>
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs text-gray-400">Starting State ID</label>
            <input type="text" value={selected.startingState}
              onChange={e => update({ startingState: e.target.value })}
              className={`${inputCls} font-mono`} placeholder="64" />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs text-gray-400">Military Strength ({selected.rebelMilStrength}%)</label>
            <input type="range" min={5} max={80} value={selected.rebelMilStrength}
              onChange={e => update({ rebelMilStrength: Number(e.target.value) })}
              className="w-full accent-red-500 cursor-pointer mt-1" />
          </div>
        </div>

        {/* Monaco editors for effects */}
        <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl overflow-hidden">
          {/* Tab bar */}
          <div className="flex border-b border-gray-800">
            {EDITOR_TABS.map(t => (
              <button key={t.id} onClick={() => setActiveTab(t.id)}
                className={`px-4 py-2.5 text-xs font-semibold transition-colors ${
                  activeTab === t.id ? 'bg-[#121212] text-amber-500 border-b-2 border-amber-500' : 'text-gray-500 hover:text-gray-300'
                }`}>
                {t.label}
              </button>
            ))}
          </div>
          <div style={{ height: '200px' }}>
            <Editor
              height="200px"
              defaultLanguage="plaintext"
              theme="vs-dark"
              value={editorValue}
              onChange={val => update({ [editorKey]: val || '' })}
              options={{ minimap: { enabled: false }, fontSize: 11, lineNumbers: 'on', scrollBeyondLastLine: false }}
            />
          </div>
        </div>
      </div>

      {/* ── Right: Code ── */}
      <div className="w-[380px] bg-[#161616] border-l border-gray-800 flex flex-col">
        <div className="flex-1 p-4 flex flex-col gap-2 overflow-hidden">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider flex items-center gap-2">
              <Code2 size={13} className="text-amber-500" /> Generated Script
            </h3>
            <button onClick={copyCode} className="flex items-center gap-1.5 text-xs text-gray-500 hover:text-amber-500 transition-colors">
              {copied ? <Check size={13} className="text-green-400" /> : <Copy size={13} />}
              {copied ? 'Copied!' : 'Copy'}
            </button>
          </div>
          <div className="flex-1 bg-[#0f0f0f] border border-gray-800 rounded-lg p-3 overflow-auto">
            <pre className="text-xs font-mono text-gray-400 whitespace-pre leading-relaxed">{generatedCode}</pre>
          </div>
        </div>
      </div>
    </div>
  );
}
