import { useMemo, useState, useRef } from 'react';
import { useModStore, type MonarchyForm, type ClaimStrength, type Pretender, type MonarchyConfig } from '../../store/useModStore';
import { AlertTriangle, Crown, Plus, Trash2, Code2, Copy, Check, Upload, X, Shield, Loader2 } from 'lucide-react';
import Editor from '@monaco-editor/react';
import { auth, uploadPortrait } from '../../services/firebase';

// ─── Data ─────────────────────────────────────────────────────────────────────

const MONARCHY_FORMS: { id: MonarchyForm; label: string; desc: string; color: string }[] = [
  { id: 'constitutional', label: 'Constitutional', desc: 'Monarch reigns but does not rule. Parliament holds power.', color: 'border-blue-500/50 bg-blue-500/5 text-blue-300' },
  { id: 'absolute', label: 'Absolute', desc: 'Monarch holds full executive and legislative authority.', color: 'border-amber-500/50 bg-amber-500/5 text-amber-300' },
  { id: 'elective', label: 'Elective', desc: 'Monarch elected by nobles or parliament for a term.', color: 'border-green-500/50 bg-green-500/5 text-green-300' },
  { id: 'theocratic', label: 'Theocratic', desc: 'Divine authority — monarch rules by religious mandate.', color: 'border-purple-500/50 bg-purple-500/5 text-purple-300' },
];

const CLAIM_COLORS: Record<ClaimStrength, string> = {
  strong: 'text-green-400 bg-green-500/10 border-green-500/40',
  weak: 'text-yellow-400 bg-yellow-500/10 border-yellow-500/40',
  disputed: 'text-red-400 bg-red-500/10 border-red-500/40',
};

const R56_IDEOLOGIES = ['democratic', 'fascism', 'communism', 'neutrality', 'monarchism'];

const newPretender = (): Pretender => ({
  id: `pretender_${Date.now()}`,
  name: 'New Pretender',
  title: 'Duke',
  countryOfOrigin: 'GER',
  claimStrength: 'weak',
  ideology: 'monarchism',
  portrait: '',
  traitId: 'r56_monarchist_sympathizer',
  restoreEventId: 'r56_monarchy.1',
  decisionId: 'r56_restore_monarchy',
});

const defaultConfig = (): MonarchyConfig => ({
  countryTag: 'GER',
  royalHouseName: 'House of Hohenzollern',
  monarchyForm: 'constitutional',
  currentMonarchName: 'Wilhelm III',
  currentMonarchTitle: 'Kaiser',
  restoreDecisionCost: 150,
  restoreRequiresWar: false,
  allowExile: true,
  pretenders: [
    {
      id: 'pre_1',
      name: 'Wilhelm III',
      title: 'Crown Prince',
      countryOfOrigin: 'GER',
      claimStrength: 'strong',
      ideology: 'monarchism',
      portrait: '',
      traitId: 'r56_monarchist_sympathizer',
      restoreEventId: 'r56_ger_monarchy.1',
      decisionId: 'r56_ger_restore_kaiser',
    }
  ],
});

// ─── Component ────────────────────────────────────────────────────────────────

export default function MonarchyEditor() {
  const { baseMod, monarchyConfig, setMonarchyConfig } = useModStore();
  const [selectedPretenderId, setSelectedPretenderId] = useState<string>(monarchyConfig.pretenders[0]?.id || '');
  const [decisionScript, setDecisionScript] = useState(
`# Restoration decision trigger\nhas_government = neutrality\nOR = {\n\thas_stability > 0.6\n\thas_war_support > 0.7\n}`
  );
  const [copied, setCopied] = useState(false);
  const [uploading, setUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const generatedCode = useMemo(() => {
    const config = monarchyConfig;
    const tag = config.countryTag.toUpperCase();
    const lines: string[] = [
      `### Monarchy Setup — ${tag} (${config.royalHouseName})`,
      `### Road to 56 — Generated by HOI4 Mod Studio`,
      ``,
      `### history/countries/${tag}.txt`,
      `set_politics = {`,
      `\truling_party = neutrality`,
      `\tlast_election = "1933.1.1"`,
      `}`,
      ``,
      `set_country_flag = r56_has_royal_house`,
      `set_variable = { r56_monarchy_form = "${config.monarchyForm}" }`,
      `set_variable = { r56_royal_house = "${config.royalHouseName}" }`,
      '',
    ];

    config.pretenders.forEach(p => {
      lines.push(`### Restoration Decision — ${p.name} (${p.claimStrength} claim)`);
      lines.push(`${p.decisionId} = {`);
      lines.push(`\ticon = r56_generic_crown`);
      lines.push(`\tcost = ${config.restoreDecisionCost}`);
      lines.push(`\tpolitical_power_cost = ${config.restoreDecisionCost}`);
      lines.push('');
      lines.push(`\tavailable = {`);
      lines.push(`\t\t${decisionScript.split('\n').join('\n\t\t')}`);
      lines.push(`\t}`);
      lines.push('');
      lines.push(`\tvisible = {`);
      lines.push(`\t\thas_country_flag = r56_has_royal_house`);
      if (config.restoreRequiresWar) lines.push(`\t\tNOT = { has_war = yes }`);
      lines.push(`\t}`);
      lines.push('');
      lines.push(`\tcomplete_effect = {`);
      lines.push(`\t\tset_politics = { ruling_party = neutrality }`);
      lines.push(`\t\tcustom_effect_tooltip = r56_monarchy_restored_tt`);
      lines.push(`\t\tcountry_event = { id = ${p.restoreEventId} days = 1 }`);
      if (config.allowExile) lines.push(`\t\tset_country_flag = r56_monarchy_restored`);
      lines.push(`\t}`);
      lines.push(`}`);
      lines.push('');
    });

    if (config.pretenders.length > 0) {
      const p = config.pretenders[0];
      lines.push(`### Country Event — Restoration`);
      lines.push(`country_event = {`);
      lines.push(`\tid = ${p.restoreEventId}`);
      lines.push(`\ttitle = ${p.restoreEventId}.t`);
      lines.push(`\tdesc = ${p.restoreEventId}.d`);
      lines.push(`\tpicture = GFX_report_event_generic_read_write`);
      lines.push(`\tis_triggered_only = yes`);
      lines.push('');
      lines.push(`\toption = {`);
      lines.push(`\t\tname = ${p.restoreEventId}.a`);
      lines.push(`\t\t# Long live the ${config.currentMonarchTitle}!`);
      lines.push(`\t\tcreate_country_leader = {`);
      lines.push(`\t\t\tname = "${p.name}"`);
      lines.push(`\t\t\tdesc = "${p.title}"`);
      lines.push(`\t\t\tideology = ${p.ideology}`);
      if (p.traitId) lines.push(`\t\t\ttraits = { ${p.traitId} }`);
      lines.push(`\t\t}`);
      lines.push(`\t}`);
      lines.push(`}`);
    }

    return lines.join('\n');
  }, [monarchyConfig, decisionScript]);

  if (baseMod !== 'road_to_56') {
    return (
      <div className="w-full h-full flex items-center justify-center bg-[#121212]">
        <div className="text-center">
          <AlertTriangle size={48} className="text-amber-500 mx-auto mb-4 opacity-60" />
          <p className="text-gray-400 text-lg font-semibold">Monarchy Editor</p>
          <p className="text-gray-600 text-sm mt-2">Exclusive to <span className="text-amber-500">Road to 56</span>.</p>
          <p className="text-gray-700 text-xs mt-1">Switch your Base Mod in ⚙️ Project Settings.</p>
        </div>
      </div>
    );
  }

  // Initialize if empty
  if (monarchyConfig.pretenders.length === 0) {
    setMonarchyConfig(defaultConfig());
  }

  const config = monarchyConfig;
  const update = (partial: Partial<MonarchyConfig>) => setMonarchyConfig(partial);
  const selectedPretender = config.pretenders.find(p => p.id === selectedPretenderId) || config.pretenders[0] || newPretender();

  const updatePretender = (partial: Partial<Pretender>) =>
    setMonarchyConfig({
      pretenders: config.pretenders.map(p => p.id === selectedPretenderId ? { ...p, ...partial } : p)
    });

  const addPretender = () => {
    const p = newPretender();
    setMonarchyConfig({ pretenders: [...config.pretenders, p] });
    setSelectedPretenderId(p.id);
  };

  const deletePretender = (id: string) => {
    const rem = config.pretenders.filter(p => p.id !== id);
    const next = rem.length ? rem : [newPretender()];
    setMonarchyConfig({ pretenders: next });
    setSelectedPretenderId(next[0].id);
  };

  const handlePortrait = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const user = auth.currentUser;
    if (user) {
      setUploading(true);
      try {
        const url = await uploadPortrait(user.uid, file, file.name);
        updatePretender({ portrait: url });
      } catch (e) {
        console.error("Cloud portrait upload failed", e);
        const reader = new FileReader();
        reader.onload = () => updatePretender({ portrait: reader.result as string });
        reader.readAsDataURL(file);
      } finally {
        setUploading(false);
      }
    } else {
      const reader = new FileReader();
      reader.onload = () => updatePretender({ portrait: reader.result as string });
      reader.readAsDataURL(file);
    }
    
    e.target.value = '';
  };

  const copyCode = () => { navigator.clipboard.writeText(generatedCode); setCopied(true); setTimeout(() => setCopied(false), 2000); };
  const inputCls = "bg-[#121212] border border-gray-700 rounded px-3 py-2 text-sm text-white focus:border-amber-500 focus:outline-none w-full";

  const monarchyFormInfo = MONARCHY_FORMS.find(m => m.id === config.monarchyForm)!;

  return (
    <div className="w-full h-full flex bg-[#121212] overflow-hidden">
      {/* ── Left Sidebar: Pretenders ── */}
      <div className="w-56 bg-[#1a1a1a] border-r border-gray-800 flex flex-col">
        {/* Royal house badge */}
        <div className="p-3 border-b border-gray-800 bg-[#161616]">
          <div className="flex items-center gap-2 mb-1">
            <Crown size={14} className="text-amber-400 flex-shrink-0" />
            <span className="text-xs font-bold text-amber-400 truncate">{config.royalHouseName}</span>
          </div>
          <div className={`text-[10px] px-2 py-0.5 rounded border inline-block font-bold ${monarchyFormInfo.color}`}>
            {monarchyFormInfo.label} Monarchy
          </div>
        </div>
        <div className="p-2 border-b border-gray-800 flex items-center justify-between">
          <span className="text-xs text-gray-600 uppercase tracking-wider">Pretenders</span>
          <button onClick={addPretender} className="p-1 rounded hover:bg-amber-500/20 text-amber-500"><Plus size={13} /></button>
        </div>
        <div className="flex-1 overflow-y-auto">
          {config.pretenders.map(p => (
            <button key={p.id} onClick={() => setSelectedPretenderId(p.id)}
              className={`w-full text-left px-3 py-3 border-b border-gray-800/60 transition-colors flex items-center gap-2 ${
                p.id === selectedPretenderId ? 'bg-amber-500/10 border-l-2 border-l-amber-500' : 'hover:bg-white/5'
              }`}>
              <div className="w-8 h-10 bg-[#121212] border border-gray-700 rounded overflow-hidden flex-shrink-0">
                {p.portrait ? <img src={p.portrait} alt="" className="w-full h-full object-cover" /> : <Crown size={14} className="m-auto mt-2 text-gray-700" />}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-xs font-semibold text-white truncate">{p.name}</p>
                <p className="text-[10px] text-gray-500 truncate">{p.title}</p>
                <span className={`text-[9px] px-1.5 py-0.5 rounded border font-bold ${CLAIM_COLORS[p.claimStrength]}`}>{p.claimStrength}</span>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* ── Center: Form ── */}
      <div className="flex-1 overflow-y-auto p-6 flex flex-col gap-5">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-amber-500/10 flex items-center justify-center">
              <Crown size={20} className="text-amber-400" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-gray-100">Monarchy Editor</h2>
              <p className="text-xs text-gray-500">Road to 56 — Royal Restoration System</p>
            </div>
          </div>
        </div>

        {/* Kingdom Setup */}
        <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-4 grid grid-cols-2 gap-4">
          <h3 className="text-xs font-semibold text-amber-500 uppercase tracking-wider col-span-2">Kingdom Configuration</h3>
          <div className="flex flex-col gap-1">
            <label className="text-xs text-gray-400">Country TAG</label>
            <input type="text" value={config.countryTag} maxLength={3}
              onChange={e => update({ countryTag: e.target.value.toUpperCase().slice(0, 3) })}
              className={`${inputCls} font-mono font-bold w-20 text-center text-amber-400`} />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs text-gray-400">Royal House Name</label>
            <input type="text" value={config.royalHouseName} onChange={e => update({ royalHouseName: e.target.value })} className={inputCls} />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs text-gray-400">Current Monarch Name</label>
            <input type="text" value={config.currentMonarchName} onChange={e => update({ currentMonarchName: e.target.value })} className={inputCls} />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs text-gray-400">Monarch Title (Kaiser, King, Shah...)</label>
            <input type="text" value={config.currentMonarchTitle} onChange={e => update({ currentMonarchTitle: e.target.value })} className={inputCls} />
          </div>
        </div>

        {/* Monarchy Form */}
        <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-4">
          <label className="text-xs font-semibold text-amber-500 uppercase tracking-wider block mb-3">Monarchy Form</label>
          <div className="grid grid-cols-2 gap-2">
            {MONARCHY_FORMS.map(m => (
              <button key={m.id} onClick={() => update({ monarchyForm: m.id })}
                className={`p-3 rounded-lg border text-left transition-all ${config.monarchyForm === m.id ? m.color : 'border-gray-700 bg-[#111] hover:border-gray-600'}`}>
                <p className="text-xs font-bold text-white">{m.label}</p>
                <p className="text-[10px] text-gray-500 mt-0.5">{m.desc}</p>
              </button>
            ))}
          </div>
        </div>

        {/* Decision options */}
        <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl p-4 flex flex-col gap-4">
          <label className="text-xs font-semibold text-amber-500 uppercase tracking-wider">Restoration Decision Options</label>
          <div className="grid grid-cols-2 gap-4">
            <div className="flex flex-col gap-1">
              <label className="text-xs text-gray-400">Political Power Cost</label>
              <input type="number" value={config.restoreDecisionCost} min={0} max={500} step={25}
                onChange={e => update({ restoreDecisionCost: Number(e.target.value) })} className={inputCls} />
            </div>
            <div className="flex flex-col gap-4 pt-1">
              <label className="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" checked={config.restoreRequiresWar}
                  onChange={e => update({ restoreRequiresWar: e.target.checked })} className="accent-amber-500 w-4 h-4" />
                <span className="text-sm text-gray-300">Only available in peacetime</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" checked={config.allowExile}
                  onChange={e => update({ allowExile: e.target.checked })} className="accent-amber-500 w-4 h-4" />
                <span className="text-sm text-gray-300">Allow restoration from exile</span>
              </label>
            </div>
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs text-gray-400">Available Trigger (shared by all decisions)</label>
            <div className="border border-gray-700 rounded overflow-hidden">
              <Editor height="130px" defaultLanguage="plaintext" theme="vs-dark" value={decisionScript}
                onChange={val => setDecisionScript(val || '')}
                options={{ minimap: { enabled: false }, fontSize: 11, lineNumbers: 'on', scrollBeyondLastLine: false }} />
            </div>
          </div>
        </div>

        {/* Pretender Properties */}
        {selectedPretender && (
          <div className="bg-[#1a1a1a] border border-gray-800 rounded-xl overflow-hidden">
            <div className="flex items-center justify-between px-4 py-3 border-b border-gray-800 bg-[#111]">
              <span className="text-xs font-semibold text-amber-400 uppercase tracking-wider flex items-center gap-2">
                <Shield size={13} /> Pretender: {selectedPretender.name}
              </span>
              <button onClick={() => deletePretender(selectedPretender.id)} disabled={config.pretenders.length === 1}
                className="text-gray-600 hover:text-red-500 transition-colors disabled:opacity-30">
                <Trash2 size={14} />
              </button>
            </div>

            <div className="p-4 grid grid-cols-2 gap-4">
              {/* Portrait */}
              <div className="col-span-2 flex items-center gap-4">
                <input ref={fileInputRef} type="file" accept="image/*" className="hidden" onChange={handlePortrait} />
                <div className="w-16 h-20 bg-[#121212] border border-gray-700 rounded overflow-hidden flex items-center justify-center flex-shrink-0">
                  {selectedPretender.portrait
                    ? <img src={selectedPretender.portrait} alt="" className="w-full h-full object-cover" />
                    : <Crown size={24} className="text-gray-700" />}
                </div>
                <div className="flex flex-col gap-2">
                  <button 
                    onClick={() => fileInputRef.current?.click()}
                    disabled={uploading}
                    title={auth.currentUser ? "Upload portrait to cloud" : "Upload portrait from disk"}
                    className="flex items-center gap-1.5 text-xs bg-amber-500/10 hover:bg-amber-500/20 text-amber-400 border border-amber-500/30 px-3 py-2 rounded transition-colors disabled:opacity-50">
                    {uploading ? <Loader2 size={12} className="animate-spin" /> : <Upload size={12} />}
                    {uploading ? 'Uploading...' : 'Upload Portrait'}
                  </button>
                  {selectedPretender.portrait && (
                    <button onClick={() => updatePretender({ portrait: '' })}
                      className="flex items-center gap-1.5 text-xs text-red-400 border border-red-500/20 px-3 py-2 rounded transition-colors">
                      <X size={12} /> Remove
                    </button>
                  )}
                </div>
              </div>

              <div className="flex flex-col gap-1">
                <label className="text-xs text-gray-400">Pretender Name</label>
                <input type="text" value={selectedPretender.name} onChange={e => updatePretender({ name: e.target.value })} className={inputCls} />
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-xs text-gray-400">Title (Duke, Prince...)</label>
                <input type="text" value={selectedPretender.title} onChange={e => updatePretender({ title: e.target.value })} className={inputCls} />
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-xs text-gray-400">Country of Origin TAG</label>
                <input type="text" value={selectedPretender.countryOfOrigin} maxLength={3}
                  onChange={e => updatePretender({ countryOfOrigin: e.target.value.toUpperCase().slice(0, 3) })}
                  className={`${inputCls} font-mono font-bold`} />
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-xs text-gray-400">Ideology</label>
                <select value={selectedPretender.ideology} onChange={e => updatePretender({ ideology: e.target.value })} className={inputCls}>
                  {R56_IDEOLOGIES.map(i => <option key={i} value={i}>{i}</option>)}
                </select>
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-xs text-gray-400">Claim Strength</label>
                <div className="flex gap-2">
                  {(['strong', 'weak', 'disputed'] as ClaimStrength[]).map(c => (
                    <button key={c} onClick={() => updatePretender({ claimStrength: c })}
                      className={`flex-1 py-1.5 rounded border text-xs font-bold capitalize transition-colors ${selectedPretender.claimStrength === c ? CLAIM_COLORS[c] : 'border-gray-700 text-gray-600 hover:text-gray-400'}`}>
                      {c}
                    </button>
                  ))}
                </div>
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-xs text-gray-400">Leader Trait ID</label>
                <input type="text" value={selectedPretender.traitId}
                  onChange={e => updatePretender({ traitId: e.target.value.toLowerCase().replace(/\s+/g, '_') })}
                  className={`${inputCls} font-mono text-amber-400`} />
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-xs text-gray-400">Restore Event ID</label>
                <input type="text" value={selectedPretender.restoreEventId}
                  onChange={e => updatePretender({ restoreEventId: e.target.value })}
                  className={`${inputCls} font-mono text-amber-400`} />
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-xs text-gray-400">Decision Script ID</label>
                <input type="text" value={selectedPretender.decisionId}
                  onChange={e => updatePretender({ decisionId: e.target.value.toLowerCase().replace(/\s+/g, '_') })}
                  className={`${inputCls} font-mono text-amber-400`} />
              </div>
            </div>
          </div>
        )}
      </div>

      {/* ── Right: Code Panel ── */}
      <div className="w-[380px] bg-[#161616] border-l border-gray-800 flex flex-col">
        {/* Summary card */}
        <div className="p-4 border-b border-gray-800">
          <div className="flex items-center gap-2 mb-3">
            <Crown size={16} className="text-amber-400" />
            <span className="text-sm font-bold text-white">{config.royalHouseName}</span>
          </div>
          <div className="grid grid-cols-2 gap-2">
            {[
              { label: 'TAG', value: config.countryTag, color: 'text-amber-400' },
              { label: 'Form', value: monarchyFormInfo.label, color: 'text-gray-300' },
              { label: 'Monarch', value: config.currentMonarchName, color: 'text-gray-300' },
              { label: 'Title', value: config.currentMonarchTitle, color: 'text-gray-300' },
              { label: 'PP Cost', value: `${config.restoreDecisionCost} PP`, color: config.restoreDecisionCost > 200 ? 'text-red-400' : 'text-green-400' },
              { label: 'Pretenders', value: String(config.pretenders.length), color: 'text-purple-400' },
            ].map(kpi => (
              <div key={kpi.label} className="bg-[#1a1a1a] border border-gray-800 rounded-lg p-2">
                <p className="text-[10px] text-gray-600 uppercase">{kpi.label}</p>
                <p className={`text-xs font-bold mt-0.5 truncate ${kpi.color}`}>{kpi.value}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Code */}
        <div className="flex-1 p-4 flex flex-col gap-2 overflow-hidden">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-semibold text-gray-400 uppercase tracking-wider flex items-center gap-2">
              <Code2 size={13} className="text-amber-400" /> Generated Script
            </h3>
            <button onClick={copyCode} className="flex items-center gap-1.5 text-xs text-gray-500 hover:text-amber-400 transition-colors">
              {copied ? <Check size={13} className="text-green-400" /> : <Copy size={13} />}
              {copied ? 'Copied!' : 'Copy'}
            </button>
          </div>
          <div className="flex-1 bg-[#0f0f0f] border border-gray-800 rounded-lg p-3 overflow-auto">
            <pre className="text-xs font-mono text-gray-400 whitespace-pre leading-relaxed">{generatedCode}</pre>
          </div>
        </div>
      </div>
    </div>
  );
}
